version: 2

models:
  - name: dbt_currencies
    description: currency data
    columns:
      - name: currency_id
        description: primary key
        tests:
          - unique
          - not_null